version: "3.8"

services:
  medibot:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend/saved_skin_model:/app/backend/saved_skin_model
      - ./backend/saved_xray_model:/app/backend/saved_xray_model
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - API_URL=http://localhost:8000
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    restart: unless-stopped
