services:
  - type: web
    name: medibot
    env: python
    buildCommand: |
      pip install -r requirements.txt
      pip install gdown
      python download_medical_models.py
    startCommand: |
      uvicorn backend.api:app --host 0.0.0.0 --port $PORT &
      python bot/bot_main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
    disk:
      name: model-cache
      mountPath: /model_cache
      sizeGB: 10
